services:
  eta_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eta_app_container
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
